# Numpy Array

In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)


numpy.ndarray

In [7]:
np.array([3.22 , 4 , 5, 6], dtype = 'float64') # hepsi float64 olur



array([3.22, 4.  , 5.  , 6.  ])

In [8]:
np.array([3.22 , 4 , 5, 6], dtype = 'int') # hepsi int olur


array([3, 4, 5, 6])

In [11]:
# sıfırdan array oluşturma

np.zeros(10, dtype = 'int') # 10 tane sıfır


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((10,2), dtype = 'int') # 10 tane 2 elemanlı array


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [19]:
print("Bir sayı giriniz: ")
sayi = int(input())


np.full((8,8), sayi) # 8x8 lik bir array oluşturur ve hepsi sayi


Bir sayı giriniz: 


array([[2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134],
       [2134, 2134, 2134, 2134, 2134, 2134, 2134, 2134]])

In [20]:
np.arange(0, 1000, 10) # 0'dan başlayarak 10'ar artırarak 1000'e kadar gider


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [22]:
np.linspace(0, 100, 5, dtype = 'int') # 0'dan başlayarak 5 eşit parçaya böler ve 100'e kadar gider


array([  0,  25,  50,  75, 100])

In [27]:
np.random.normal(10, 4, (3,4)) # 10'dan başlayarak 4'e kadar 3x4'lük bir array oluşturur


array([[ 5.50900375,  6.76185882, 14.23260758,  8.69547024],
       [ 8.88299419,  9.06170318,  2.6009325 ,  7.54052595],
       [14.53425533, 10.57658059,  9.48798776, 14.01135289]])

In [29]:
np.random.randint(0, 10, (3,4),dtype='int') # 0'dan başlayarak 10'a kadar 3x4'lük bir array oluşturur



array([[2, 6, 1, 6],
       [5, 2, 7, 1],
       [7, 2, 8, 1]])

### Numpy Array Özellikleri

* ndim : kaç boyutlu bir array olduğunu gösterir
* shape : array'in şeklini gösterir
* size : array'in eleman sayısını gösterir
* dtype : array'in elemanlarının tipini gösterir
* itemsize : array'in elemanlarının byte'ını gösterir
* nbytes : array'in elemanlarının toplam byte'ını gösterir
* real : array'in gerçek kısmını gösterir
* imag : array'in sanal kısmını gösterir
* data : array'in verilerinin adresini gösterir

In [31]:
np.random.randint(10, size = 10,dtype='int') # 10'dan başlayarak 10 tane sayı üretir


array([0, 2, 3, 1, 5, 1, 0, 9, 8, 1])

In [32]:
a = np.random.randint(10, size = 10,dtype='int')

In [34]:
a.ndim # kaç boyutlu bir array olduğunu gösterir


1

In [35]:
a.shape # array'in şeklini gösterir


(10,)

In [36]:
a.size # array'in eleman sayısını gösterir


10

In [37]:
a.dtype # array'in elemanlarının tipini gösterir


dtype('int64')

In [38]:
a.itemsize # array'in elemanlarının byte'ını gösterir


8

In [39]:
a.nbytes # array'in elemanlarının toplam byte'ını gösterir


80

In [40]:
a.real # array'in gerçek kısmını gösterir


array([8, 6, 1, 8, 6, 6, 8, 5, 0, 6])

In [41]:
a.imag # array'in sanal kısmını gösterir


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
a.data # array'in verilerinin adresini gösterir


In [43]:
b = np.random.randint(10, size = (3,4),dtype='int')


In [45]:
b.ndim


2

In [46]:
b.size

12

In [47]:
b.shape

(3, 4)

### Yenide Şekillendirme ---> reshaping


In [48]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10).reshape(3,3) # 1'den başlayarak 10'a kadar 3x3'lük bir array oluşturur


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a = np.arange(1,10)
a 


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a.ndim

1

In [55]:
b = a.reshape(1,9)


In [56]:
b.ndim

2

### Birleştirme ---> Concatenation


In [57]:
x = np.array([1,2,3])
y = np.array([4,5,6])




In [59]:
np.concatenate([x,y]) # x ve y'yi birleştirir


array([1, 2, 3, 4, 5, 6])

In [60]:
z = np.array([7,8,9])


In [61]:
np.concatenate([x,y,z]) # x,y,z'yi birleştirir


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# iki boyutlu array'leri birleştirme

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

np.concatenate([a,b])



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.concatenate([a,b], axis = 1) # a ve b'yi yatay olarak birleştirir


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
np.concatenate([a,b], axis = 0) # a ve b'yi dikey olarak birleştirir


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.concatenate([a,b], axis = None) # a ve b'yi tek bir array'e birleştirir


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.concatenate([a,a]) 


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Array Ayırma ---> Splitting


In [67]:
a = np.arange(1,10)

np.split(a, [3,5,7]) # a'yı 3,5,7 noktalarına göre ayırır

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [74]:
x = np.array([1,2,3,192,218,3,2,1])

np.split(x, [3,5]) # x'i 3,5 noktalarına göre ayırır



[array([1, 2, 3]), array([192, 218]), array([3, 2, 1])]

In [75]:
b,c,d = np.split(x, [3,5])


In [76]:
b

array([1, 2, 3])

In [77]:
c

array([192, 218])

In [78]:
d

array([3, 2, 1])

In [82]:
# İki boyutlu array'leri ayırma

m = np.arange(16).reshape(4,4)

m


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.vsplit(m, [2]) # m'yi 2. satıra göre ayırır


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [84]:
ust, alt = np.vsplit(m, [2])


In [85]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.hsplit(m, [2]) # m'yi 2. sütuna göre ayırır


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [89]:
sag,sol = np.hsplit(m, [2])


In [90]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [91]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Sıralama ---> Sorting


In [104]:
v = np.array([2,1,4,3,5])


In [105]:
v

array([2, 1, 4, 3, 5])

In [108]:
np.sort(v) # v'yi sıralar. v'yi değiştirmez. v.sort() ise v'yi değiştirir


array([1, 2, 3, 4, 5])

In [109]:
v

array([2, 1, 4, 3, 5])

In [111]:
# iki boyutlu array'leri sıralama

m = np.random.normal(20,5,(3,3))


In [112]:
m

array([[27.56812743, 17.18419633, 22.49807844],
       [18.32397268, 19.4675863 , 20.37384878],
       [21.81121221, 22.74319609, 24.17034559]])

In [113]:
np.sort(m) # m'yi sıralar. m'yi değiştirmez. m.sort() ise m'yi değiştirir


array([[17.18419633, 22.49807844, 27.56812743],
       [18.32397268, 19.4675863 , 20.37384878],
       [21.81121221, 22.74319609, 24.17034559]])

In [114]:
np.sort(m, axis = 0) # m'yi dikey olarak sıralar


array([[18.32397268, 17.18419633, 20.37384878],
       [21.81121221, 19.4675863 , 22.49807844],
       [27.56812743, 22.74319609, 24.17034559]])

In [115]:
np.sort(m, axis = 1) # m'yi yatay olarak sıralar


array([[17.18419633, 22.49807844, 27.56812743],
       [18.32397268, 19.4675863 , 20.37384878],
       [21.81121221, 22.74319609, 24.17034559]])

In [116]:
import numpy as np
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])