# Index ile elemana erişme

In [1]:
import numpy as np

a = np.random.randint(10, size = 10)
a


array([5, 4, 7, 5, 8, 6, 7, 5, 5, 1], dtype=int32)

In [10]:
a[0] 

np.int32(8)

In [11]:
a[-1]

np.int32(1)

In [12]:
a[0] = 100
a

array([100,   0,   6,   0,   1,   3,   0,   0,   7,   1], dtype=int32)

In [13]:
m = np.random.randint(10, size = (3,5))
m


array([[9, 5, 4, 2, 1],
       [1, 7, 8, 9, 7],
       [3, 9, 6, 3, 4]], dtype=int32)

In [14]:
m[0,0]


np.int32(9)

In [15]:
m[0,1]

np.int32(5)

In [16]:
m[1,0]

np.int32(1)

In [19]:
m[1,4] = 22.2
m

array([[ 9,  5,  4,  2,  1],
       [ 1,  7,  8,  9, 22],
       [ 3,  9,  6,  3,  4]], dtype=int32)

### Array alt küme işlemleri

In [20]:
a = np.arange(20,30)
a


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
a[0:3]

array([20, 21, 22])

In [23]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [25]:
a[1::7] # 1'den başlayarak 7'şer ilerler


array([21, 28])

In [28]:
# iki boyutlu slice işlemleri

m = np.random.randint(10, size = (5,5))
m




array([[8, 3, 8, 0, 2],
       [6, 0, 9, 2, 5],
       [3, 6, 2, 0, 4],
       [6, 7, 7, 4, 4],
       [7, 1, 5, 6, 9]], dtype=int32)

In [29]:
m[:,0] # 0. sütunu alır


array([8, 6, 3, 6, 7], dtype=int32)

In [30]:
m[:,1] # 1. sütunu alır


array([3, 0, 6, 7, 1], dtype=int32)

In [32]:
m[1,:] # 1. satırı alır


array([6, 0, 9, 2, 5], dtype=int32)

In [33]:
m[0:2, 0:3] # 0. satır ve 0. sütun arasındaki elemanları alır


array([[8, 3, 8],
       [6, 0, 9]], dtype=int32)

In [35]:
m[::, :2] # 0. ve 1. sütunları alır



array([[8, 3],
       [6, 0],
       [3, 6],
       [6, 7],
       [7, 1]], dtype=int32)

In [36]:
m[::-1, ::-1] # tüm elemanları ters çevirir



array([[9, 6, 5, 1, 7],
       [4, 4, 7, 7, 6],
       [4, 0, 2, 6, 3],
       [5, 2, 9, 0, 6],
       [2, 0, 8, 3, 8]], dtype=int32)

### Alt Küme üzerinde işlemler


In [37]:
a  = np.random.randint(10, size = (5,5))
a


array([[3, 0, 8, 8, 9],
       [5, 5, 4, 8, 0],
       [2, 3, 4, 5, 0],
       [7, 4, 9, 3, 7],
       [2, 0, 3, 2, 1]], dtype=int32)

In [38]:
alt_a = a[0:3, 0:2]
alt_a

array([[3, 0],
       [5, 5],
       [2, 3]], dtype=int32)

In [46]:
alt_a[0,0] = 100
alt_a[1,1] = 200
alt_a



array([[100,   0],
       [  5, 200],
       [  2,   3]], dtype=int32)

In [47]:
a 

array([[100,   0,   8,   8,   9],
       [  5, 200,   4,   8,   0],
       [  2,   3,   4,   5,   0],
       [  7,   4,   9,   3,   7],
       [  2,   0,   3,   2,   1]], dtype=int32)

In [49]:
m  = np.random.randint(10, size = (5,5))
m


array([[4, 4, 1, 9, 0],
       [3, 7, 0, 7, 2],
       [5, 6, 4, 3, 5],
       [0, 3, 0, 7, 5],
       [1, 6, 7, 4, 0]], dtype=int32)

In [51]:
alt_b = m[0:3, 0:2].copy() # alt_b'yi kopyalar
alt_b
m

array([[4, 4, 1, 9, 0],
       [3, 7, 0, 7, 2],
       [5, 6, 4, 3, 5],
       [0, 3, 0, 7, 5],
       [1, 6, 7, 4, 0]], dtype=int32)

In [52]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b # alt_b'de değişiklik yapılır


array([[100,   4],
       [  3, 200],
       [  5,   6]], dtype=int32)

In [53]:
m # m'de değişiklik yoktur


array([[4, 4, 1, 9, 0],
       [3, 7, 0, 7, 2],
       [5, 6, 4, 3, 5],
       [0, 3, 0, 7, 5],
       [1, 6, 7, 4, 0]], dtype=int32)

### Fancy Index ile elemanlara erişme


In [54]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [55]:
v[1]

np.int64(3)

In [56]:
v[2]

np.int64(6)

In [57]:
v[5]

np.int64(15)

In [58]:
v[[1,2,5]] # 1, 2, 5. elemanları alır


array([ 3,  6, 15])

In [60]:
[v[1], v[2], v[5]] # aynı işlemi yapar


[np.int64(3), np.int64(6), np.int64(15)]

In [61]:
al_getir = [1,2,5]

In [62]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [63]:
v[al_getir] # aynı işlemi yapar


array([ 3,  6, 15])

In [65]:
# iki boyutlu array'de fancy index ile elemanlara erişme

m = np.arange(9).reshape(3,3)
m




array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
satir = np.array([0,1])
sutun = np.array([1,2])


In [67]:
m[satir, sutun]


array([1, 5])

In [68]:
# basit index ile fancy index

m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
m[0,[1,2]] # 0. satır ve 1. ve 2. sütunları alır. Basit index ile fancy index birleştirme


array([1, 2])

In [71]:
# slice ile fancy index

m[0:, [1,2]] # 0. satır ve 1. ve 2. sütunları alır. Slice ile fancy index birleştirme


array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu eleman işlemleri

In [73]:
v = np.array([1,2,3,4,5])
v > 5 # v'nin elemanları 5'ten büyük mü?


array([False, False, False, False, False])

In [75]:
v > 2    # v'nin elemanları 2'den büyük mü?


array([False, False,  True,  True,  True])

In [76]:
v[v>2] # v'nin elemanları 2'den büyük olanları alır


array([3, 4, 5])

In [77]:
v[v<2] # v'nin elemanları 2'den küçük olanları alır


array([1])

In [78]:
v[v>=2] # v'nin elemanları 2'den büyük veya eşit olanları alır


array([2, 3, 4, 5])

In [79]:
v[v<=2] # v'nin elemanları 2'den küçük veya eşit olanları alır


array([1, 2])

In [80]:
v[v!=2] # v'nin elemanları 2'den farklı olanları alır


array([1, 3, 4, 5])

In [81]:
v * 2 # v'nin elemanlarını 2 ile çarpar


array([ 2,  4,  6,  8, 10])

In [82]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [83]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

### Matematiksel İşlemler

In [84]:
v = np.array([1,2,3,4,5])

In [85]:
v - 1

array([0, 1, 2, 3, 4])

In [86]:
v + 1

array([2, 3, 4, 5, 6])

In [87]:
v * 2

array([ 2,  4,  6,  8, 10])

In [88]:
v / 12

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667])

In [89]:
v % 2

array([1, 0, 1, 0, 1])

In [90]:
# ufunc ile matematiksel işlemler

np.subtract(v, 1) # v'nin elemanlarını 1'den çıkarır


array([0, 1, 2, 3, 4])

In [91]:
np.add(v, 1) # v'nin elemanlarını 1'e ekler


array([2, 3, 4, 5, 6])

In [95]:
np.multiply(v,4) # v'nin elemanlarını 2 ile çarpar


array([ 4,  8, 12, 16, 20])

In [96]:
np.divide(v, 5) # v'nin elemanlarını 5'e böler


array([0.2, 0.4, 0.6, 0.8, 1. ])

In [97]:
np.power(v, 2) # v'nin elemanlarını 2. kuvvetine alır


array([ 1,  4,  9, 16, 25])

In [98]:
np.mod(v, 2) # v'nin elemanlarını 2'ye böler ve kalanı alır


array([1, 0, 1, 0, 1])

In [99]:
np.sqrt(v) # v'nin elemanlarının karekökünü alır


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [100]:
np.exp(v) # v'nin elemanlarının e'nin kuvvetini alır


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [101]:
np.log(v) # v'nin elemanlarının doğal logaritmasını alır


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [102]:
np.sin(v) # v'nin elemanlarının sinüsünü alır


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [103]:
np.cos(v) # v'nin elemanlarının kosinüsünü alır


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [104]:
np.tan(v) # v'nin elemanlarının tanjantını alır


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [110]:
np.log10(v) # v'nin elemanlarının 10 tabanında logaritmasını alır


array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [111]:
np.log2(v) # v'nin elemanlarının 2 tabanında logaritmasını alır


array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

### Cheatsheet

https://images.datacamp.com/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf

### Numpy ile iki bilinmeyenli denklem çözümü


- 5 * x0 + x1 = 12
- x0 + 3 * x1 = 10

In [113]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

a


array([[5, 1],
       [1, 3]])

In [114]:
b

array([12, 10])

In [116]:
x = np.linalg.solve(a,b) # a ve b'yi çözer
x


array([1.85714286, 2.71428571])