# Pandas 


## Pandas Serisi Oluşturma

In [1]:
import pandas as pd

pd.Series([10,20,30,40,50])


0    10
1    20
2    30
3    40
4    50
dtype: int64

In [2]:
seri = pd.Series([10,20,30,40,50])


In [3]:
type(seri)


pandas.core.series.Series

In [17]:
seri.axes # Serinin eksenlerini gösterir
 

[RangeIndex(start=0, stop=5, step=1)]

In [18]:
seri.dtype # Serinin veri tipini gösterir


dtype('int64')

In [20]:
seri.ndim # Serinin boyutunu gösterir


1

In [21]:
seri.size # Serinin eleman sayısını gösterir


5

In [22]:
seri.head(1) # Serinin ilk elemanını gösterir


0    10
dtype: int64

In [23]:
seri.tail(1) # Serinin son elemanını gösterir


4    50
dtype: int64

In [24]:
seri.index # Serinin index'ini gösterir


RangeIndex(start=0, stop=5, step=1)

In [25]:
seri.values # Serinin değerlerini gösterir


array([10, 20, 30, 40, 50])

In [26]:
seri.describe() # Serinin istatistiksel özelliklerini gösterir


count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [27]:
seri.mean() # Serinin ortalamasını gösterir


np.float64(30.0)

In [28]:
seri.sum() # Serinin toplamını gösterir


np.int64(150)

In [29]:
seri.max() # Serinin en büyük değerini gösterir


np.int64(50)

In [30]:
seri.min() # Serinin en küçük değerini gösterir


np.int64(10)

In [31]:
seri.std() # Serinin standart sapmasını gösterir


np.float64(15.811388300841896)

In [32]:
seri.var() # Serinin varyansını gösterir


np.float64(250.0)

In [33]:
seri.median() # Serinin medyanını gösterir


np.float64(30.0)

In [34]:
seri.quantile(0.5) # Serinin kuantilini gösterir


np.float64(30.0)

In [35]:
seri.cumsum() # Serinin kümülatif toplamını gösterir


0     10
1     30
2     60
3    100
4    150
dtype: int64

In [36]:
seri.cumprod() # Serinin kümülatif çarpımını gösterir


0          10
1         200
2        6000
3      240000
4    12000000
dtype: int64

In [37]:
# indeks isimlendirmesi

seri.index = ["a","b","c","d","e"]

seri



a    10
b    20
c    30
d    40
e    50
dtype: int64

In [40]:
seri =pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
seri

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [42]:
seri["a"]

np.int64(10)

In [44]:
# sozluk üzerinden liste oluşturma

sozluk = {"a":10, "b":20, "c":30, "d":40, "e":50}
seri2 = pd.Series(sozluk)
seri2




a    10
b    20
c    30
d    40
e    50
dtype: int64

In [45]:
# iki seriyi birleştirme

seri1 = pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
seri2 = pd.Series([5,4,3,2,1], index = ["a","b","c","d","e"])

pd.concat([seri1,seri2])


a    10
b    20
c    30
d    40
e    50
a     5
b     4
c     3
d     2
e     1
dtype: int64

## Eleman İşlemleri

In [47]:
import numpy as np
a  = np.array([12,23,34,45,56])
seri3 = pd.Series(a)
seri3 


0    12
1    23
2    34
3    45
4    56
dtype: int64

In [49]:
seri[1]

C:\Users\Burak\AppData\Local\Temp\ipykernel_15488\3700278937.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  seri[1]


np.int64(20)

In [50]:
seri[0:3]

a    10
b    20
c    30
dtype: int64

In [51]:
seri = pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
seri


a    10
b    20
c    30
d    40
e    50
dtype: int64

In [52]:
seri.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [54]:
seri.keys

<bound method Series.keys of a    10
b    20
c    30
d    40
e    50
dtype: int64>

In [55]:
list(seri.items())


[('a', 10), ('b', 20), ('c', 30), ('d', 40), ('e', 50)]

In [56]:
seri.values


array([10, 20, 30, 40, 50])

In [58]:
# Eleman Sorgulama

"a" in seri # seride a ismi var mı? 


True

In [59]:
# Fancy Indexing

seri[["a","b"]]



a    10
b    20
dtype: int64

In [60]:
seri["a"] = 2031
seri["a"]

np.int64(2031)

In [61]:
seri["a":"d"]

a    2031
b      20
c      30
d      40
dtype: int64

## Pandas DataFrame Oluşturma


In [62]:
l = [1,2,3,4,5]
l


[1, 2, 3, 4, 5]

In [63]:
pd.DataFrame(l)


0
0  1
1  2
2  3
3  4
4  5

In [64]:
pd.DataFrame(l, columns = ["ad"])


ad
0   1
1   2
2   3
3   4
4   5

In [65]:
m = np.arange(1,10).reshape(3,3)

pd.DataFrame(m, index = ["a","b","c"], columns = ["x","y","z"])



x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [66]:
# df isimlendirme 

df = pd.DataFrame(m, index = ["a","b","c"], columns = ["x","y","z"])
df

x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [69]:
df.head(1) # ilk satırı gösterir

x  y  z
a  1  2  3

In [70]:
df.tail(1) # son satırı gösterir


x  y  z
c  7  8  9

In [72]:
df.index # index'i gösterir


Index(['a', 'b', 'c'], dtype='object')

In [73]:
df.columns # sütun isimlerini gösterir


Index(['x', 'y', 'z'], dtype='object')

In [74]:
df.values # değerleri gösterir


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
df.describe() # istatistiksel bilgileri gösterir


x    y    z
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [76]:
df.mean() # ortalama değeri gösterir


x    4.0
y    5.0
z    6.0
dtype: float64

In [77]:
df.sum() # toplam değeri gösterir


x    12
y    15
z    18
dtype: int64

In [78]:
df.max() # en büyük değeri gösterir


x    7
y    8
z    9
dtype: int64

In [79]:
df.axes # eksenleri gösterir


[Index(['a', 'b', 'c'], dtype='object'),
 Index(['x', 'y', 'z'], dtype='object')]

In [80]:
type(df)


pandas.core.frame.DataFrame

In [81]:
df.shape # boyutu gösterir


(3, 3)

In [82]:
type(df.values)



df.dtypes # veri tiplerini gösterir



x    int64
y    int64
z    int64
dtype: object

In [115]:
# Eleman İşlemleri

s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [116]:
sozluk = {"s1":s1, "s2":s2, "s3":s3}
sozluk


{'s1': array([1, 0, 0, 0, 9], dtype=int32),
 's2': array([5, 6, 6, 0, 1], dtype=int32),
 's3': array([3, 3, 6, 3, 9], dtype=int32)}

In [117]:
df = pd.DataFrame(sozluk)
df

s1  s2  s3
0   1   5   3
1   0   6   3
2   0   6   6
3   0   0   3
4   9   1   9

In [118]:
df[0:1]

s1  s2  s3
0   1   5   3

In [119]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [120]:
df.index = ["a","b","c","d","e"]
df

s1  s2  s3
a   1   5   3
b   0   6   3
c   0   6   6
d   0   0   3
e   9   1   9

In [121]:
df["c":"e"]

s1  s2  s3
c   0   6   6
d   0   0   3
e   9   1   9

In [122]:
# Silme

df.drop("a", axis = 0) # a satırını siler


s1  s2  s3
b   0   6   3
c   0   6   6
d   0   0   3
e   9   1   9

In [123]:
df # Ana yapıda değişiklik yok


s1  s2  s3
a   1   5   3
b   0   6   3
c   0   6   6
d   0   0   3
e   9   1   9

In [124]:
df.drop("b", axis = 0, inplace = True) # Ana yapıda değişiklik yapar
df

s1  s2  s3
a   1   5   3
c   0   6   6
d   0   0   3
e   9   1   9

In [125]:
df

s1  s2  s3
a   1   5   3
c   0   6   6
d   0   0   3
e   9   1   9

In [126]:
# Fancy Indexing

l = ["c","d"]
df.drop(l, axis = 0, inplace = True) # c ve d satırlarını siler
df


s1  s2  s3
a   1   5   3
e   9   1   9

In [134]:
# Değişkenler İçin

"s1" in df.columns # a sütunu var mı?


True

In [136]:
l = ["s1","s4","s2"]

In [137]:
for i in l:
    print(i in df)


True
False
True


In [138]:
df

s1  s2  s3
a   1   5   3
e   9   1   9

In [140]:
df["s1"]

a    1
e    9
Name: s1, dtype: int32

In [141]:
df["s4"] = df["s1"] / df["s2"]
df


s1  s2  s3   s4
a   1   5   3  0.2
e   9   1   9  9.0

In [142]:
# değişken silme

df.drop("s4", axis = 1, inplace = True)
df



s1  s2  s3
a   1   5   3
e   9   1   9

In [143]:
df

s1  s2  s3
a   1   5   3
e   9   1   9